// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Azure.NetApp.Inputs
{

    public sealed class VolumeGroupSapHanaVolumeDataProtectionReplicationArgs : global::Pulumi.ResourceArgs
    {
        [Input("endpointType")]
        public Input<string>? EndpointType { get; set; }

        [Input("remoteVolumeLocation", required: true)]
        public Input<string> RemoteVolumeLocation { get; set; } = null!;

        [Input("remoteVolumeResourceId", required: true)]
        public Input<string> RemoteVolumeResourceId { get; set; } = null!;

        [Input("replicationFrequency", required: true)]
        public Input<string> ReplicationFrequency { get; set; } = null!;

        public VolumeGroupSapHanaVolumeDataProtectionReplicationArgs()
        {
        }
        public static new VolumeGroupSapHanaVolumeDataProtectionReplicationArgs Empty => new VolumeGroupSapHanaVolumeDataProtectionReplicationArgs();
    }
}
