// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Azure.NetApp.Inputs
{

    public sealed class VolumeBucketWithServerServerGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("certificatePem")]
        private Input<string>? _certificatePem;

        /// <summary>
        /// Base64-encoded PEM blob containing the server certificate concatenated with the private key. Used when the certificate is supplied directly instead of via Key Vault. Mutually exclusive with `KeyVault`.
        /// </summary>
        public Input<string>? CertificatePem
        {
            get => _certificatePem;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _certificatePem = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The DNS name that resolves to the bucket endpoint IP address.
        /// </summary>
        [Input("fqdn", required: true)]
        public Input<string> Fqdn { get; set; } = null!;

        /// <summary>
        /// Behaviour when an existing certificate already matches during a certificate rotation. Possible values are `Update` and `Fail`. Defaults to `Fail`.
        /// </summary>
        [Input("onCertificateConflictAction")]
        public Input<string>? OnCertificateConflictAction { get; set; }

        public VolumeBucketWithServerServerGetArgs()
        {
        }
        public static new VolumeBucketWithServerServerGetArgs Empty => new VolumeBucketWithServerServerGetArgs();
    }
}
