// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * Manages an Azure App Configuration Feature.
 *
 * > **Note:** App Configuration Features are provisioned using a Data Plane API which requires the role `App Configuration Data Owner` on either the App Configuration or a parent scope (such as the Resource Group/Subscription). [More information can be found in the Azure Documentation for App Configuration](https://docs.microsoft.com/azure/azure-app-configuration/concept-enable-rbac#azure-built-in-roles-for-azure-app-configuration). This is similar to providing App Configuration Keys.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as azure from "@pulumi/azure";
 *
 * const example = new azure.core.ResourceGroup("example", {
 *     name: "example-resources",
 *     location: "West Europe",
 * });
 * const appconf = new azure.appconfiguration.ConfigurationStore("appconf", {
 *     name: "appConf1",
 *     resourceGroupName: example.name,
 *     location: example.location,
 * });
 * const current = azure.core.getClientConfig({});
 * const appconfDataowner = new azure.authorization.Assignment("appconf_dataowner", {
 *     scope: appconf.id,
 *     roleDefinitionName: "App Configuration Data Owner",
 *     principalId: current.then(current => current.objectId),
 * });
 * const test = new azure.appconfiguration.ConfigurationFeature("test", {
 *     configurationStoreId: appconf.id,
 *     description: "test description",
 *     name: "test-ackey",
 *     label: "test-ackeylabel",
 *     enabled: true,
 * });
 * ```
 *
 * ## Import
 *
 * App Configuration Features can be imported using the `resource id`, e.g.
 *
 * ```sh
 * $ pulumi import azure:appconfiguration/configurationFeature:ConfigurationFeature test https://appconfname1.azconfig.io/kv/.appconfig.featureflag%2FkeyName?label=labelName
 * ```
 *
 * If you wish to import with an empty label then simply leave the label's name blank:
 *
 * ```sh
 * $ pulumi import azure:appconfiguration/configurationFeature:ConfigurationFeature test https://appconfname1.azconfig.io/kv/.appconfig.featureflag%2FkeyName?label=
 * ```
 */
export class ConfigurationFeature extends pulumi.CustomResource {
    /**
     * Get an existing ConfigurationFeature resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ConfigurationFeatureState, opts?: pulumi.CustomResourceOptions): ConfigurationFeature {
        return new ConfigurationFeature(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'azure:appconfiguration/configurationFeature:ConfigurationFeature';

    /**
     * Returns true if the given object is an instance of ConfigurationFeature.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ConfigurationFeature {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ConfigurationFeature.__pulumiType;
    }

    /**
     * Specifies the id of the App Configuration. Changing this forces a new resource to be created.
     */
    public readonly configurationStoreId!: pulumi.Output<string>;
    /**
     * The description of the App Configuration Feature.
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * The status of the App Configuration Feature. By default, this is set to false.
     */
    public readonly enabled!: pulumi.Output<boolean | undefined>;
    public readonly etag!: pulumi.Output<string>;
    /**
     * The key of the App Configuration Feature. The value for `name` will be used if this is unspecified. Changing this forces a new resource to be created.
     */
    public readonly key!: pulumi.Output<string>;
    /**
     * The label of the App Configuration Feature. Changing this forces a new resource to be created.
     */
    public readonly label!: pulumi.Output<string | undefined>;
    /**
     * Should this App Configuration Feature be Locked to prevent changes?
     */
    public readonly locked!: pulumi.Output<boolean | undefined>;
    /**
     * The name of the App Configuration Feature. Changing this forces a new resource to be created.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * A number representing the value of the percentage required to enable this feature.
     */
    public readonly percentageFilterValue!: pulumi.Output<number | undefined>;
    /**
     * A mapping of tags to assign to the resource.
     */
    public readonly tags!: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * A `targetingFilter` block as defined below.
     */
    public readonly targetingFilters!: pulumi.Output<outputs.appconfiguration.ConfigurationFeatureTargetingFilter[] | undefined>;
    /**
     * A `timewindowFilter` block as defined below.
     */
    public readonly timewindowFilters!: pulumi.Output<outputs.appconfiguration.ConfigurationFeatureTimewindowFilter[] | undefined>;

    /**
     * Create a ConfigurationFeature resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ConfigurationFeatureArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ConfigurationFeatureArgs | ConfigurationFeatureState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ConfigurationFeatureState | undefined;
            resourceInputs["configurationStoreId"] = state ? state.configurationStoreId : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["enabled"] = state ? state.enabled : undefined;
            resourceInputs["etag"] = state ? state.etag : undefined;
            resourceInputs["key"] = state ? state.key : undefined;
            resourceInputs["label"] = state ? state.label : undefined;
            resourceInputs["locked"] = state ? state.locked : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["percentageFilterValue"] = state ? state.percentageFilterValue : undefined;
            resourceInputs["tags"] = state ? state.tags : undefined;
            resourceInputs["targetingFilters"] = state ? state.targetingFilters : undefined;
            resourceInputs["timewindowFilters"] = state ? state.timewindowFilters : undefined;
        } else {
            const args = argsOrState as ConfigurationFeatureArgs | undefined;
            if ((!args || args.configurationStoreId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'configurationStoreId'");
            }
            resourceInputs["configurationStoreId"] = args ? args.configurationStoreId : undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["enabled"] = args ? args.enabled : undefined;
            resourceInputs["etag"] = args ? args.etag : undefined;
            resourceInputs["key"] = args ? args.key : undefined;
            resourceInputs["label"] = args ? args.label : undefined;
            resourceInputs["locked"] = args ? args.locked : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["percentageFilterValue"] = args ? args.percentageFilterValue : undefined;
            resourceInputs["tags"] = args ? args.tags : undefined;
            resourceInputs["targetingFilters"] = args ? args.targetingFilters : undefined;
            resourceInputs["timewindowFilters"] = args ? args.timewindowFilters : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ConfigurationFeature.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ConfigurationFeature resources.
 */
export interface ConfigurationFeatureState {
    /**
     * Specifies the id of the App Configuration. Changing this forces a new resource to be created.
     */
    configurationStoreId?: pulumi.Input<string>;
    /**
     * The description of the App Configuration Feature.
     */
    description?: pulumi.Input<string>;
    /**
     * The status of the App Configuration Feature. By default, this is set to false.
     */
    enabled?: pulumi.Input<boolean>;
    etag?: pulumi.Input<string>;
    /**
     * The key of the App Configuration Feature. The value for `name` will be used if this is unspecified. Changing this forces a new resource to be created.
     */
    key?: pulumi.Input<string>;
    /**
     * The label of the App Configuration Feature. Changing this forces a new resource to be created.
     */
    label?: pulumi.Input<string>;
    /**
     * Should this App Configuration Feature be Locked to prevent changes?
     */
    locked?: pulumi.Input<boolean>;
    /**
     * The name of the App Configuration Feature. Changing this forces a new resource to be created.
     */
    name?: pulumi.Input<string>;
    /**
     * A number representing the value of the percentage required to enable this feature.
     */
    percentageFilterValue?: pulumi.Input<number>;
    /**
     * A mapping of tags to assign to the resource.
     */
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * A `targetingFilter` block as defined below.
     */
    targetingFilters?: pulumi.Input<pulumi.Input<inputs.appconfiguration.ConfigurationFeatureTargetingFilter>[]>;
    /**
     * A `timewindowFilter` block as defined below.
     */
    timewindowFilters?: pulumi.Input<pulumi.Input<inputs.appconfiguration.ConfigurationFeatureTimewindowFilter>[]>;
}

/**
 * The set of arguments for constructing a ConfigurationFeature resource.
 */
export interface ConfigurationFeatureArgs {
    /**
     * Specifies the id of the App Configuration. Changing this forces a new resource to be created.
     */
    configurationStoreId: pulumi.Input<string>;
    /**
     * The description of the App Configuration Feature.
     */
    description?: pulumi.Input<string>;
    /**
     * The status of the App Configuration Feature. By default, this is set to false.
     */
    enabled?: pulumi.Input<boolean>;
    etag?: pulumi.Input<string>;
    /**
     * The key of the App Configuration Feature. The value for `name` will be used if this is unspecified. Changing this forces a new resource to be created.
     */
    key?: pulumi.Input<string>;
    /**
     * The label of the App Configuration Feature. Changing this forces a new resource to be created.
     */
    label?: pulumi.Input<string>;
    /**
     * Should this App Configuration Feature be Locked to prevent changes?
     */
    locked?: pulumi.Input<boolean>;
    /**
     * The name of the App Configuration Feature. Changing this forces a new resource to be created.
     */
    name?: pulumi.Input<string>;
    /**
     * A number representing the value of the percentage required to enable this feature.
     */
    percentageFilterValue?: pulumi.Input<number>;
    /**
     * A mapping of tags to assign to the resource.
     */
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * A `targetingFilter` block as defined below.
     */
    targetingFilters?: pulumi.Input<pulumi.Input<inputs.appconfiguration.ConfigurationFeatureTargetingFilter>[]>;
    /**
     * A `timewindowFilter` block as defined below.
     */
    timewindowFilters?: pulumi.Input<pulumi.Input<inputs.appconfiguration.ConfigurationFeatureTimewindowFilter>[]>;
}
