// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Azure.Network.Inputs
{

    public sealed class ApplicationGatewayPrivateLinkConfigurationIpConfigurationGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the IP configuration.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// Is this the Primary IP Configuration?
        /// </summary>
        [Input("primary", required: true)]
        public Input<bool> Primary { get; set; } = null!;

        /// <summary>
        /// The Static IP Address which should be used.
        /// </summary>
        [Input("privateIpAddress")]
        public Input<string>? PrivateIpAddress { get; set; }

        /// <summary>
        /// The allocation method used for the Private IP Address. Possible values are `Dynamic` and `Static`.
        /// </summary>
        [Input("privateIpAddressAllocation", required: true)]
        public Input<string> PrivateIpAddressAllocation { get; set; } = null!;

        /// <summary>
        /// The ID of the subnet the private link configuration should connect to.
        /// </summary>
        [Input("subnetId", required: true)]
        public Input<string> SubnetId { get; set; } = null!;

        public ApplicationGatewayPrivateLinkConfigurationIpConfigurationGetArgs()
        {
        }
        public static new ApplicationGatewayPrivateLinkConfigurationIpConfigurationGetArgs Empty => new ApplicationGatewayPrivateLinkConfigurationIpConfigurationGetArgs();
    }
}
