// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Azure.Network.Inputs
{

    public sealed class ExpressRouteCircuitPeeringIpv6Args : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// A boolean value indicating whether the IPv6 peering is enabled. Defaults to `true`.
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// A `microsoft_peering` block as defined below.
        /// </summary>
        [Input("microsoftPeering")]
        public Input<Inputs.ExpressRouteCircuitPeeringIpv6MicrosoftPeeringArgs>? MicrosoftPeering { get; set; }

        /// <summary>
        /// A subnet for the primary link.
        /// </summary>
        [Input("primaryPeerAddressPrefix", required: true)]
        public Input<string> PrimaryPeerAddressPrefix { get; set; } = null!;

        /// <summary>
        /// The ID of the Route Filter. Only available when `peering_type` is set to `MicrosoftPeering`.
        /// 
        /// &gt; **Note:** `ipv6` can be specified when `peering_type` is `MicrosoftPeering` or `AzurePrivatePeering`
        /// </summary>
        [Input("routeFilterId")]
        public Input<string>? RouteFilterId { get; set; }

        /// <summary>
        /// A subnet for the secondary link.
        /// </summary>
        [Input("secondaryPeerAddressPrefix", required: true)]
        public Input<string> SecondaryPeerAddressPrefix { get; set; } = null!;

        public ExpressRouteCircuitPeeringIpv6Args()
        {
        }
        public static new ExpressRouteCircuitPeeringIpv6Args Empty => new ExpressRouteCircuitPeeringIpv6Args();
    }
}
