archives:
- id: archive
  name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
before:
  hooks:
  - make tfgen
blobs:
- bucket: get.pulumi.com
  folder: releases/plugins/
  ids:
  - archive
  provider: s3
  region: us-west-2
builds:
- binary: pulumi-resource-azure
  dir: provider
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - windows
  - linux
  ldflags:
  - -X github.com/pulumi/pulumi-azure/provider/v4/pkg/version.Version={{.Tag}}
  main: ./cmd/pulumi-resource-azure/
changelog:
  skip: true
release:
  prerelease: auto
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'
