// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Azure.AppService.Outputs
{

    [OutputType]
    public sealed class AppFlexConsumptionAuthSettingsV2MicrosoftV2
    {
        /// <summary>
        /// Specifies a list of Allowed Audiences that will be requested as part of Microsoft Sign-In authentication.
        /// </summary>
        public readonly ImmutableArray<string> AllowedAudiences;
        /// <summary>
        /// The OAuth 2.0 client ID that was created for the app used for authentication.
        /// </summary>
        public readonly string ClientId;
        /// <summary>
        /// The app setting name containing the OAuth 2.0 client secret that was created for the app used for authentication.
        /// 
        /// !&gt; **Note:** A setting with this name must exist in `app_settings` to function correctly.
        /// </summary>
        public readonly string ClientSecretSettingName;
        /// <summary>
        /// The list of Login scopes that should be requested as part of Microsoft Account authentication.
        /// </summary>
        public readonly ImmutableArray<string> LoginScopes;

        [OutputConstructor]
        private AppFlexConsumptionAuthSettingsV2MicrosoftV2(
            ImmutableArray<string> allowedAudiences,

            string clientId,

            string clientSecretSettingName,

            ImmutableArray<string> loginScopes)
        {
            AllowedAudiences = allowedAudiences;
            ClientId = clientId;
            ClientSecretSettingName = clientSecretSettingName;
            LoginScopes = loginScopes;
        }
    }
}
