// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Azure.AppService.Outputs
{

    [OutputType]
    public sealed class WindowsWebAppSiteConfigAutoHealSettingActionCustomAction
    {
        /// <summary>
        /// The executable to run for the `custom_action`.
        /// </summary>
        public readonly string Executable;
        /// <summary>
        /// The parameters to pass to the specified `executable`.
        /// </summary>
        public readonly string? Parameters;

        [OutputConstructor]
        private WindowsWebAppSiteConfigAutoHealSettingActionCustomAction(
            string executable,

            string? parameters)
        {
            Executable = executable;
            Parameters = parameters;
        }
    }
}
