// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.azure.compute.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class BastionHostIpConfigurationArgs extends com.pulumi.resources.ResourceArgs {

    public static final BastionHostIpConfigurationArgs Empty = new BastionHostIpConfigurationArgs();

    /**
     * The name of the IP configuration. Changing this forces a new resource to be created.
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return The name of the IP configuration. Changing this forces a new resource to be created.
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    /**
     * Reference to a Public IP Address to associate with this Bastion Host. Changing this forces a new resource to be created.
     * 
     */
    @Import(name="publicIpAddressId", required=true)
    private Output<String> publicIpAddressId;

    /**
     * @return Reference to a Public IP Address to associate with this Bastion Host. Changing this forces a new resource to be created.
     * 
     */
    public Output<String> publicIpAddressId() {
        return this.publicIpAddressId;
    }

    /**
     * Reference to a subnet in which this Bastion Host has been created. Changing this forces a new resource to be created.
     * 
     * &gt; **Note:** The Subnet used for the Bastion Host must have the name `AzureBastionSubnet` and the subnet mask must be at least a `/26`.
     * 
     */
    @Import(name="subnetId", required=true)
    private Output<String> subnetId;

    /**
     * @return Reference to a subnet in which this Bastion Host has been created. Changing this forces a new resource to be created.
     * 
     * &gt; **Note:** The Subnet used for the Bastion Host must have the name `AzureBastionSubnet` and the subnet mask must be at least a `/26`.
     * 
     */
    public Output<String> subnetId() {
        return this.subnetId;
    }

    private BastionHostIpConfigurationArgs() {}

    private BastionHostIpConfigurationArgs(BastionHostIpConfigurationArgs $) {
        this.name = $.name;
        this.publicIpAddressId = $.publicIpAddressId;
        this.subnetId = $.subnetId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(BastionHostIpConfigurationArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private BastionHostIpConfigurationArgs $;

        public Builder() {
            $ = new BastionHostIpConfigurationArgs();
        }

        public Builder(BastionHostIpConfigurationArgs defaults) {
            $ = new BastionHostIpConfigurationArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param name The name of the IP configuration. Changing this forces a new resource to be created.
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the IP configuration. Changing this forces a new resource to be created.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param publicIpAddressId Reference to a Public IP Address to associate with this Bastion Host. Changing this forces a new resource to be created.
         * 
         * @return builder
         * 
         */
        public Builder publicIpAddressId(Output<String> publicIpAddressId) {
            $.publicIpAddressId = publicIpAddressId;
            return this;
        }

        /**
         * @param publicIpAddressId Reference to a Public IP Address to associate with this Bastion Host. Changing this forces a new resource to be created.
         * 
         * @return builder
         * 
         */
        public Builder publicIpAddressId(String publicIpAddressId) {
            return publicIpAddressId(Output.of(publicIpAddressId));
        }

        /**
         * @param subnetId Reference to a subnet in which this Bastion Host has been created. Changing this forces a new resource to be created.
         * 
         * &gt; **Note:** The Subnet used for the Bastion Host must have the name `AzureBastionSubnet` and the subnet mask must be at least a `/26`.
         * 
         * @return builder
         * 
         */
        public Builder subnetId(Output<String> subnetId) {
            $.subnetId = subnetId;
            return this;
        }

        /**
         * @param subnetId Reference to a subnet in which this Bastion Host has been created. Changing this forces a new resource to be created.
         * 
         * &gt; **Note:** The Subnet used for the Bastion Host must have the name `AzureBastionSubnet` and the subnet mask must be at least a `/26`.
         * 
         * @return builder
         * 
         */
        public Builder subnetId(String subnetId) {
            return subnetId(Output.of(subnetId));
        }

        public BastionHostIpConfigurationArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("BastionHostIpConfigurationArgs", "name");
            }
            if ($.publicIpAddressId == null) {
                throw new MissingRequiredPropertyException("BastionHostIpConfigurationArgs", "publicIpAddressId");
            }
            if ($.subnetId == null) {
                throw new MissingRequiredPropertyException("BastionHostIpConfigurationArgs", "subnetId");
            }
            return $;
        }
    }

}
