// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.azure.storage.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetBlobArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetBlobArgs Empty = new GetBlobArgs();

    /**
     * A map of custom blob metadata.
     * 
     */
    @Import(name="metadata")
    private @Nullable Output<Map<String,String>> metadata;

    /**
     * @return A map of custom blob metadata.
     * 
     */
    public Optional<Output<Map<String,String>>> metadata() {
        return Optional.ofNullable(this.metadata);
    }

    /**
     * The name of the Blob.
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return The name of the Blob.
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    /**
     * The ID of the Storage Container where the Blob exists.
     * 
     */
    @Import(name="storageContainerId", required=true)
    private Output<String> storageContainerId;

    /**
     * @return The ID of the Storage Container where the Blob exists.
     * 
     */
    public Output<String> storageContainerId() {
        return this.storageContainerId;
    }

    private GetBlobArgs() {}

    private GetBlobArgs(GetBlobArgs $) {
        this.metadata = $.metadata;
        this.name = $.name;
        this.storageContainerId = $.storageContainerId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetBlobArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetBlobArgs $;

        public Builder() {
            $ = new GetBlobArgs();
        }

        public Builder(GetBlobArgs defaults) {
            $ = new GetBlobArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param metadata A map of custom blob metadata.
         * 
         * @return builder
         * 
         */
        public Builder metadata(@Nullable Output<Map<String,String>> metadata) {
            $.metadata = metadata;
            return this;
        }

        /**
         * @param metadata A map of custom blob metadata.
         * 
         * @return builder
         * 
         */
        public Builder metadata(Map<String,String> metadata) {
            return metadata(Output.of(metadata));
        }

        /**
         * @param name The name of the Blob.
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the Blob.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param storageContainerId The ID of the Storage Container where the Blob exists.
         * 
         * @return builder
         * 
         */
        public Builder storageContainerId(Output<String> storageContainerId) {
            $.storageContainerId = storageContainerId;
            return this;
        }

        /**
         * @param storageContainerId The ID of the Storage Container where the Blob exists.
         * 
         * @return builder
         * 
         */
        public Builder storageContainerId(String storageContainerId) {
            return storageContainerId(Output.of(storageContainerId));
        }

        public GetBlobArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("GetBlobArgs", "name");
            }
            if ($.storageContainerId == null) {
                throw new MissingRequiredPropertyException("GetBlobArgs", "storageContainerId");
            }
            return $;
        }
    }

}
