// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package management

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-azure/sdk/v5/go/azure"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "azure:management/group:Group":
		r = &Group{}
	case "azure:management/groupPolicyAssignment:GroupPolicyAssignment":
		r = &GroupPolicyAssignment{}
	case "azure:management/groupPolicyExemption:GroupPolicyExemption":
		r = &GroupPolicyExemption{}
	case "azure:management/groupPolicyRemediation:GroupPolicyRemediation":
		r = &GroupPolicyRemediation{}
	case "azure:management/groupSubscriptionAssociation:GroupSubscriptionAssociation":
		r = &GroupSubscriptionAssociation{}
	case "azure:management/groupTemplateDeployment:GroupTemplateDeployment":
		r = &GroupTemplateDeployment{}
	case "azure:management/lock:Lock":
		r = &Lock{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := azure.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"azure",
		"management/group",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"azure",
		"management/groupPolicyAssignment",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"azure",
		"management/groupPolicyExemption",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"azure",
		"management/groupPolicyRemediation",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"azure",
		"management/groupSubscriptionAssociation",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"azure",
		"management/groupTemplateDeployment",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"azure",
		"management/lock",
		&module{version},
	)
}
