// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Azure.Network.Outputs
{

    [OutputType]
    public sealed class VpnServerConfigurationRadius
    {
        /// <summary>
        /// One or more `client_root_certificate` blocks as defined below.
        /// </summary>
        public readonly ImmutableArray<Outputs.VpnServerConfigurationRadiusClientRootCertificate> ClientRootCertificates;
        /// <summary>
        /// One or more `server_root_certificate` blocks as defined below.
        /// </summary>
        public readonly ImmutableArray<Outputs.VpnServerConfigurationRadiusServerRootCertificate> ServerRootCertificates;
        /// <summary>
        /// One or more `server` blocks as defined below.
        /// </summary>
        public readonly ImmutableArray<Outputs.VpnServerConfigurationRadiusServer> Servers;

        [OutputConstructor]
        private VpnServerConfigurationRadius(
            ImmutableArray<Outputs.VpnServerConfigurationRadiusClientRootCertificate> clientRootCertificates,

            ImmutableArray<Outputs.VpnServerConfigurationRadiusServerRootCertificate> serverRootCertificates,

            ImmutableArray<Outputs.VpnServerConfigurationRadiusServer> servers)
        {
            ClientRootCertificates = clientRootCertificates;
            ServerRootCertificates = serverRootCertificates;
            Servers = servers;
        }
    }
}
