// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Azure.DevTest.Inputs
{

    public sealed class ScheduleHourlyRecurrenceArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Minutes of the hour the schedule will run.
        /// </summary>
        [Input("minute", required: true)]
        public Input<int> Minute { get; set; } = null!;

        public ScheduleHourlyRecurrenceArgs()
        {
        }
        public static new ScheduleHourlyRecurrenceArgs Empty => new ScheduleHourlyRecurrenceArgs();
    }
}
