// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.azure.compute.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class LinuxVirtualMachineAdditionalCapabilities {
    /**
     * @return Should the capacity to enable Data Disks of the `UltraSSD_LRS` storage account type be supported on this Virtual Machine? Defaults to `false`.
     * 
     */
    private final @Nullable Boolean ultraSsdEnabled;

    @CustomType.Constructor
    private LinuxVirtualMachineAdditionalCapabilities(@CustomType.Parameter("ultraSsdEnabled") @Nullable Boolean ultraSsdEnabled) {
        this.ultraSsdEnabled = ultraSsdEnabled;
    }

    /**
     * @return Should the capacity to enable Data Disks of the `UltraSSD_LRS` storage account type be supported on this Virtual Machine? Defaults to `false`.
     * 
     */
    public Optional<Boolean> ultraSsdEnabled() {
        return Optional.ofNullable(this.ultraSsdEnabled);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(LinuxVirtualMachineAdditionalCapabilities defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private @Nullable Boolean ultraSsdEnabled;

        public Builder() {
    	      // Empty
        }

        public Builder(LinuxVirtualMachineAdditionalCapabilities defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.ultraSsdEnabled = defaults.ultraSsdEnabled;
        }

        public Builder ultraSsdEnabled(@Nullable Boolean ultraSsdEnabled) {
            this.ultraSsdEnabled = ultraSsdEnabled;
            return this;
        }        public LinuxVirtualMachineAdditionalCapabilities build() {
            return new LinuxVirtualMachineAdditionalCapabilities(ultraSsdEnabled);
        }
    }
}
