// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.azure.redhatopenshift.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ClusterClusterProfile {
    /**
     * @return The custom domain for the cluster. For more info, see [Prepare a custom domain for your cluster](https://docs.microsoft.com/azure/openshift/tutorial-create-cluster#prepare-a-custom-domain-for-your-cluster-optional). Changing this forces a new resource to be created.
     * 
     */
    private String domain;
    /**
     * @return Whether Federal Information Processing Standard (FIPS) validated cryptographic modules are used. Defaults to `false`. Changing this forces a new resource to be created.
     * 
     */
    private @Nullable Boolean fipsEnabled;
    /**
     * @return The name of a Resource Group which will be created to host VMs of Azure Red Hat OpenShift Cluster. The value cannot contain uppercase characters. Defaults to `aro-{domain}`. Changing this forces a new resource to be created.
     * 
     */
    private @Nullable String managedResourceGroupName;
    /**
     * @return The Red Hat pull secret for the cluster. For more info, see [Get a Red Hat pull secret](https://learn.microsoft.com/azure/openshift/tutorial-create-cluster#get-a-red-hat-pull-secret-optional). Changing this forces a new resource to be created.
     * 
     */
    private @Nullable String pullSecret;
    /**
     * @return The resource group that the cluster profile is attached to.
     * 
     */
    private @Nullable String resourceGroupId;
    /**
     * @return The version of the OpenShift cluster. Available versions can be found with the Azure CLI command `az aro get-versions --location &lt;region&gt;`. Changing this forces a new resource to be created.
     * 
     */
    private String version;

    private ClusterClusterProfile() {}
    /**
     * @return The custom domain for the cluster. For more info, see [Prepare a custom domain for your cluster](https://docs.microsoft.com/azure/openshift/tutorial-create-cluster#prepare-a-custom-domain-for-your-cluster-optional). Changing this forces a new resource to be created.
     * 
     */
    public String domain() {
        return this.domain;
    }
    /**
     * @return Whether Federal Information Processing Standard (FIPS) validated cryptographic modules are used. Defaults to `false`. Changing this forces a new resource to be created.
     * 
     */
    public Optional<Boolean> fipsEnabled() {
        return Optional.ofNullable(this.fipsEnabled);
    }
    /**
     * @return The name of a Resource Group which will be created to host VMs of Azure Red Hat OpenShift Cluster. The value cannot contain uppercase characters. Defaults to `aro-{domain}`. Changing this forces a new resource to be created.
     * 
     */
    public Optional<String> managedResourceGroupName() {
        return Optional.ofNullable(this.managedResourceGroupName);
    }
    /**
     * @return The Red Hat pull secret for the cluster. For more info, see [Get a Red Hat pull secret](https://learn.microsoft.com/azure/openshift/tutorial-create-cluster#get-a-red-hat-pull-secret-optional). Changing this forces a new resource to be created.
     * 
     */
    public Optional<String> pullSecret() {
        return Optional.ofNullable(this.pullSecret);
    }
    /**
     * @return The resource group that the cluster profile is attached to.
     * 
     */
    public Optional<String> resourceGroupId() {
        return Optional.ofNullable(this.resourceGroupId);
    }
    /**
     * @return The version of the OpenShift cluster. Available versions can be found with the Azure CLI command `az aro get-versions --location &lt;region&gt;`. Changing this forces a new resource to be created.
     * 
     */
    public String version() {
        return this.version;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ClusterClusterProfile defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String domain;
        private @Nullable Boolean fipsEnabled;
        private @Nullable String managedResourceGroupName;
        private @Nullable String pullSecret;
        private @Nullable String resourceGroupId;
        private String version;
        public Builder() {}
        public Builder(ClusterClusterProfile defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.domain = defaults.domain;
    	      this.fipsEnabled = defaults.fipsEnabled;
    	      this.managedResourceGroupName = defaults.managedResourceGroupName;
    	      this.pullSecret = defaults.pullSecret;
    	      this.resourceGroupId = defaults.resourceGroupId;
    	      this.version = defaults.version;
        }

        @CustomType.Setter
        public Builder domain(String domain) {
            if (domain == null) {
              throw new MissingRequiredPropertyException("ClusterClusterProfile", "domain");
            }
            this.domain = domain;
            return this;
        }
        @CustomType.Setter
        public Builder fipsEnabled(@Nullable Boolean fipsEnabled) {

            this.fipsEnabled = fipsEnabled;
            return this;
        }
        @CustomType.Setter
        public Builder managedResourceGroupName(@Nullable String managedResourceGroupName) {

            this.managedResourceGroupName = managedResourceGroupName;
            return this;
        }
        @CustomType.Setter
        public Builder pullSecret(@Nullable String pullSecret) {

            this.pullSecret = pullSecret;
            return this;
        }
        @CustomType.Setter
        public Builder resourceGroupId(@Nullable String resourceGroupId) {

            this.resourceGroupId = resourceGroupId;
            return this;
        }
        @CustomType.Setter
        public Builder version(String version) {
            if (version == null) {
              throw new MissingRequiredPropertyException("ClusterClusterProfile", "version");
            }
            this.version = version;
            return this;
        }
        public ClusterClusterProfile build() {
            final var _resultValue = new ClusterClusterProfile();
            _resultValue.domain = domain;
            _resultValue.fipsEnabled = fipsEnabled;
            _resultValue.managedResourceGroupName = managedResourceGroupName;
            _resultValue.pullSecret = pullSecret;
            _resultValue.resourceGroupId = resourceGroupId;
            _resultValue.version = version;
            return _resultValue;
        }
    }
}
