// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.azure.datafactory.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class LinkedServiceAzureFileStorageKeyVaultPassword {
    /**
     * @return Specifies the name of an existing Key Vault Data Factory Linked Service.
     * 
     */
    private String linkedServiceName;
    /**
     * @return Specifies the secret name in Azure Key Vault that stores Azure File Storage password.
     * 
     */
    private String secretName;

    private LinkedServiceAzureFileStorageKeyVaultPassword() {}
    /**
     * @return Specifies the name of an existing Key Vault Data Factory Linked Service.
     * 
     */
    public String linkedServiceName() {
        return this.linkedServiceName;
    }
    /**
     * @return Specifies the secret name in Azure Key Vault that stores Azure File Storage password.
     * 
     */
    public String secretName() {
        return this.secretName;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(LinkedServiceAzureFileStorageKeyVaultPassword defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String linkedServiceName;
        private String secretName;
        public Builder() {}
        public Builder(LinkedServiceAzureFileStorageKeyVaultPassword defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.linkedServiceName = defaults.linkedServiceName;
    	      this.secretName = defaults.secretName;
        }

        @CustomType.Setter
        public Builder linkedServiceName(String linkedServiceName) {
            if (linkedServiceName == null) {
              throw new MissingRequiredPropertyException("LinkedServiceAzureFileStorageKeyVaultPassword", "linkedServiceName");
            }
            this.linkedServiceName = linkedServiceName;
            return this;
        }
        @CustomType.Setter
        public Builder secretName(String secretName) {
            if (secretName == null) {
              throw new MissingRequiredPropertyException("LinkedServiceAzureFileStorageKeyVaultPassword", "secretName");
            }
            this.secretName = secretName;
            return this;
        }
        public LinkedServiceAzureFileStorageKeyVaultPassword build() {
            final var _resultValue = new LinkedServiceAzureFileStorageKeyVaultPassword();
            _resultValue.linkedServiceName = linkedServiceName;
            _resultValue.secretName = secretName;
            return _resultValue;
        }
    }
}
