// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.azure.databricks.outputs;

import com.pulumi.azure.databricks.outputs.GetWorkspaceCustomParameter;
import com.pulumi.azure.databricks.outputs.GetWorkspaceEnhancedSecurityCompliance;
import com.pulumi.azure.databricks.outputs.GetWorkspaceManagedDiskIdentity;
import com.pulumi.azure.databricks.outputs.GetWorkspaceStorageAccountIdentity;
import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import javax.annotation.Nullable;

@CustomType
public final class GetWorkspaceResult {
    /**
     * @return A `custom_parameters` block as documented below.
     * *
     * 
     */
    private List<GetWorkspaceCustomParameter> customParameters;
    /**
     * @return An `enhanced_security_compliance` block as documented below.
     * 
     */
    private List<GetWorkspaceEnhancedSecurityCompliance> enhancedSecurityCompliances;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    /**
     * @return The Azure location where the Databricks Workspace exists.
     * 
     */
    private String location;
    /**
     * @return A `managed_disk_identity` block as documented below.
     * 
     */
    private List<GetWorkspaceManagedDiskIdentity> managedDiskIdentities;
    private String name;
    private String resourceGroupName;
    /**
     * @return SKU of this Databricks Workspace.
     * 
     */
    private String sku;
    /**
     * @return A `storage_account_identity` block as documented below.
     * 
     */
    private List<GetWorkspaceStorageAccountIdentity> storageAccountIdentities;
    /**
     * @return A mapping of tags to assign to the Databricks Workspace.
     * 
     */
    private @Nullable Map<String,String> tags;
    /**
     * @return Unique ID of this Databricks Workspace in Databricks management plane.
     * 
     */
    private String workspaceId;
    /**
     * @return URL this Databricks Workspace is accessible on.
     * 
     */
    private String workspaceUrl;

    private GetWorkspaceResult() {}
    /**
     * @return A `custom_parameters` block as documented below.
     * *
     * 
     */
    public List<GetWorkspaceCustomParameter> customParameters() {
        return this.customParameters;
    }
    /**
     * @return An `enhanced_security_compliance` block as documented below.
     * 
     */
    public List<GetWorkspaceEnhancedSecurityCompliance> enhancedSecurityCompliances() {
        return this.enhancedSecurityCompliances;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return The Azure location where the Databricks Workspace exists.
     * 
     */
    public String location() {
        return this.location;
    }
    /**
     * @return A `managed_disk_identity` block as documented below.
     * 
     */
    public List<GetWorkspaceManagedDiskIdentity> managedDiskIdentities() {
        return this.managedDiskIdentities;
    }
    public String name() {
        return this.name;
    }
    public String resourceGroupName() {
        return this.resourceGroupName;
    }
    /**
     * @return SKU of this Databricks Workspace.
     * 
     */
    public String sku() {
        return this.sku;
    }
    /**
     * @return A `storage_account_identity` block as documented below.
     * 
     */
    public List<GetWorkspaceStorageAccountIdentity> storageAccountIdentities() {
        return this.storageAccountIdentities;
    }
    /**
     * @return A mapping of tags to assign to the Databricks Workspace.
     * 
     */
    public Map<String,String> tags() {
        return this.tags == null ? Map.of() : this.tags;
    }
    /**
     * @return Unique ID of this Databricks Workspace in Databricks management plane.
     * 
     */
    public String workspaceId() {
        return this.workspaceId;
    }
    /**
     * @return URL this Databricks Workspace is accessible on.
     * 
     */
    public String workspaceUrl() {
        return this.workspaceUrl;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetWorkspaceResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<GetWorkspaceCustomParameter> customParameters;
        private List<GetWorkspaceEnhancedSecurityCompliance> enhancedSecurityCompliances;
        private String id;
        private String location;
        private List<GetWorkspaceManagedDiskIdentity> managedDiskIdentities;
        private String name;
        private String resourceGroupName;
        private String sku;
        private List<GetWorkspaceStorageAccountIdentity> storageAccountIdentities;
        private @Nullable Map<String,String> tags;
        private String workspaceId;
        private String workspaceUrl;
        public Builder() {}
        public Builder(GetWorkspaceResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.customParameters = defaults.customParameters;
    	      this.enhancedSecurityCompliances = defaults.enhancedSecurityCompliances;
    	      this.id = defaults.id;
    	      this.location = defaults.location;
    	      this.managedDiskIdentities = defaults.managedDiskIdentities;
    	      this.name = defaults.name;
    	      this.resourceGroupName = defaults.resourceGroupName;
    	      this.sku = defaults.sku;
    	      this.storageAccountIdentities = defaults.storageAccountIdentities;
    	      this.tags = defaults.tags;
    	      this.workspaceId = defaults.workspaceId;
    	      this.workspaceUrl = defaults.workspaceUrl;
        }

        @CustomType.Setter
        public Builder customParameters(List<GetWorkspaceCustomParameter> customParameters) {
            if (customParameters == null) {
              throw new MissingRequiredPropertyException("GetWorkspaceResult", "customParameters");
            }
            this.customParameters = customParameters;
            return this;
        }
        public Builder customParameters(GetWorkspaceCustomParameter... customParameters) {
            return customParameters(List.of(customParameters));
        }
        @CustomType.Setter
        public Builder enhancedSecurityCompliances(List<GetWorkspaceEnhancedSecurityCompliance> enhancedSecurityCompliances) {
            if (enhancedSecurityCompliances == null) {
              throw new MissingRequiredPropertyException("GetWorkspaceResult", "enhancedSecurityCompliances");
            }
            this.enhancedSecurityCompliances = enhancedSecurityCompliances;
            return this;
        }
        public Builder enhancedSecurityCompliances(GetWorkspaceEnhancedSecurityCompliance... enhancedSecurityCompliances) {
            return enhancedSecurityCompliances(List.of(enhancedSecurityCompliances));
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetWorkspaceResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder location(String location) {
            if (location == null) {
              throw new MissingRequiredPropertyException("GetWorkspaceResult", "location");
            }
            this.location = location;
            return this;
        }
        @CustomType.Setter
        public Builder managedDiskIdentities(List<GetWorkspaceManagedDiskIdentity> managedDiskIdentities) {
            if (managedDiskIdentities == null) {
              throw new MissingRequiredPropertyException("GetWorkspaceResult", "managedDiskIdentities");
            }
            this.managedDiskIdentities = managedDiskIdentities;
            return this;
        }
        public Builder managedDiskIdentities(GetWorkspaceManagedDiskIdentity... managedDiskIdentities) {
            return managedDiskIdentities(List.of(managedDiskIdentities));
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetWorkspaceResult", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder resourceGroupName(String resourceGroupName) {
            if (resourceGroupName == null) {
              throw new MissingRequiredPropertyException("GetWorkspaceResult", "resourceGroupName");
            }
            this.resourceGroupName = resourceGroupName;
            return this;
        }
        @CustomType.Setter
        public Builder sku(String sku) {
            if (sku == null) {
              throw new MissingRequiredPropertyException("GetWorkspaceResult", "sku");
            }
            this.sku = sku;
            return this;
        }
        @CustomType.Setter
        public Builder storageAccountIdentities(List<GetWorkspaceStorageAccountIdentity> storageAccountIdentities) {
            if (storageAccountIdentities == null) {
              throw new MissingRequiredPropertyException("GetWorkspaceResult", "storageAccountIdentities");
            }
            this.storageAccountIdentities = storageAccountIdentities;
            return this;
        }
        public Builder storageAccountIdentities(GetWorkspaceStorageAccountIdentity... storageAccountIdentities) {
            return storageAccountIdentities(List.of(storageAccountIdentities));
        }
        @CustomType.Setter
        public Builder tags(@Nullable Map<String,String> tags) {

            this.tags = tags;
            return this;
        }
        @CustomType.Setter
        public Builder workspaceId(String workspaceId) {
            if (workspaceId == null) {
              throw new MissingRequiredPropertyException("GetWorkspaceResult", "workspaceId");
            }
            this.workspaceId = workspaceId;
            return this;
        }
        @CustomType.Setter
        public Builder workspaceUrl(String workspaceUrl) {
            if (workspaceUrl == null) {
              throw new MissingRequiredPropertyException("GetWorkspaceResult", "workspaceUrl");
            }
            this.workspaceUrl = workspaceUrl;
            return this;
        }
        public GetWorkspaceResult build() {
            final var _resultValue = new GetWorkspaceResult();
            _resultValue.customParameters = customParameters;
            _resultValue.enhancedSecurityCompliances = enhancedSecurityCompliances;
            _resultValue.id = id;
            _resultValue.location = location;
            _resultValue.managedDiskIdentities = managedDiskIdentities;
            _resultValue.name = name;
            _resultValue.resourceGroupName = resourceGroupName;
            _resultValue.sku = sku;
            _resultValue.storageAccountIdentities = storageAccountIdentities;
            _resultValue.tags = tags;
            _resultValue.workspaceId = workspaceId;
            _resultValue.workspaceUrl = workspaceUrl;
            return _resultValue;
        }
    }
}
