# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = [
    'CustomLocationAuthentication',
    'GetCustomLocationAuthenticationResult',
]

@pulumi.output_type
class CustomLocationAuthentication(dict):
    def __init__(__self__, *,
                 value: builtins.str,
                 type: Optional[builtins.str] = None):
        """
        :param builtins.str value: Specifies the value of authentication.
        :param builtins.str type: Specifies the type of authentication.
        """
        pulumi.set(__self__, "value", value)
        if type is not None:
            pulumi.set(__self__, "type", type)

    @property
    @pulumi.getter
    def value(self) -> builtins.str:
        """
        Specifies the value of authentication.
        """
        return pulumi.get(self, "value")

    @property
    @pulumi.getter
    def type(self) -> Optional[builtins.str]:
        """
        Specifies the type of authentication.
        """
        return pulumi.get(self, "type")


@pulumi.output_type
class GetCustomLocationAuthenticationResult(dict):
    def __init__(__self__, *,
                 type: builtins.str,
                 value: builtins.str):
        """
        :param builtins.str type: The type of authentication.
        :param builtins.str value: The value of authentication.
        """
        pulumi.set(__self__, "type", type)
        pulumi.set(__self__, "value", value)

    @property
    @pulumi.getter
    def type(self) -> builtins.str:
        """
        The type of authentication.
        """
        return pulumi.get(self, "type")

    @property
    @pulumi.getter
    def value(self) -> builtins.str:
        """
        The value of authentication.
        """
        return pulumi.get(self, "value")


