// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Azure.Storage.Outputs
{

    [OutputType]
    public sealed class GetPolicyRuleActionBaseBlobResult
    {
        /// <summary>
        /// Whether a blob should automatically be tiered from cool back to hot if it's accessed again after being tiered to cool.
        /// </summary>
        public readonly bool AutoTierToHotFromCoolEnabled;
        /// <summary>
        /// The age in days after creation to delete the blob snapshot.
        /// </summary>
        public readonly int DeleteAfterDaysSinceCreationGreaterThan;
        /// <summary>
        /// The age in days after last access time to delete the blob.
        /// </summary>
        public readonly int DeleteAfterDaysSinceLastAccessTimeGreaterThan;
        /// <summary>
        /// The age in days after last modification to delete the blob.
        /// </summary>
        public readonly int DeleteAfterDaysSinceModificationGreaterThan;
        /// <summary>
        /// The age in days after creation to archive storage.
        /// </summary>
        public readonly int TierToArchiveAfterDaysSinceCreationGreaterThan;
        /// <summary>
        /// The age in days after last access time to tier blobs to archive storage.
        /// </summary>
        public readonly int TierToArchiveAfterDaysSinceLastAccessTimeGreaterThan;
        /// <summary>
        /// The age in days after last tier change to the blobs to skip to be archived.
        /// </summary>
        public readonly int TierToArchiveAfterDaysSinceLastTierChangeGreaterThan;
        /// <summary>
        /// The age in days after last modification to tier blobs to archive storage.
        /// </summary>
        public readonly int TierToArchiveAfterDaysSinceModificationGreaterThan;
        /// <summary>
        /// Optional The age in days after creation to cold storage. Supports blob currently at Hot tier.
        /// </summary>
        public readonly int TierToColdAfterDaysSinceCreationGreaterThan;
        /// <summary>
        /// The age in days after last access time to tier blobs to cold storage. Supports blob currently at Hot tier.
        /// </summary>
        public readonly int TierToColdAfterDaysSinceLastAccessTimeGreaterThan;
        /// <summary>
        /// The age in days after last modification to tier blobs to cold storage. Supports blob currently at Hot tier.
        /// </summary>
        public readonly int TierToColdAfterDaysSinceModificationGreaterThan;
        /// <summary>
        /// Optional The age in days after creation to cool storage. Supports blob currently at Hot tier.
        /// </summary>
        public readonly int TierToCoolAfterDaysSinceCreationGreaterThan;
        /// <summary>
        /// The age in days after last access time to tier blobs to cool storage. Supports blob currently at Hot tier.
        /// </summary>
        public readonly int TierToCoolAfterDaysSinceLastAccessTimeGreaterThan;
        /// <summary>
        /// The age in days after last modification to tier blobs to cool storage. Supports blob currently at Hot tier.
        /// </summary>
        public readonly int TierToCoolAfterDaysSinceModificationGreaterThan;

        [OutputConstructor]
        private GetPolicyRuleActionBaseBlobResult(
            bool autoTierToHotFromCoolEnabled,

            int deleteAfterDaysSinceCreationGreaterThan,

            int deleteAfterDaysSinceLastAccessTimeGreaterThan,

            int deleteAfterDaysSinceModificationGreaterThan,

            int tierToArchiveAfterDaysSinceCreationGreaterThan,

            int tierToArchiveAfterDaysSinceLastAccessTimeGreaterThan,

            int tierToArchiveAfterDaysSinceLastTierChangeGreaterThan,

            int tierToArchiveAfterDaysSinceModificationGreaterThan,

            int tierToColdAfterDaysSinceCreationGreaterThan,

            int tierToColdAfterDaysSinceLastAccessTimeGreaterThan,

            int tierToColdAfterDaysSinceModificationGreaterThan,

            int tierToCoolAfterDaysSinceCreationGreaterThan,

            int tierToCoolAfterDaysSinceLastAccessTimeGreaterThan,

            int tierToCoolAfterDaysSinceModificationGreaterThan)
        {
            AutoTierToHotFromCoolEnabled = autoTierToHotFromCoolEnabled;
            DeleteAfterDaysSinceCreationGreaterThan = deleteAfterDaysSinceCreationGreaterThan;
            DeleteAfterDaysSinceLastAccessTimeGreaterThan = deleteAfterDaysSinceLastAccessTimeGreaterThan;
            DeleteAfterDaysSinceModificationGreaterThan = deleteAfterDaysSinceModificationGreaterThan;
            TierToArchiveAfterDaysSinceCreationGreaterThan = tierToArchiveAfterDaysSinceCreationGreaterThan;
            TierToArchiveAfterDaysSinceLastAccessTimeGreaterThan = tierToArchiveAfterDaysSinceLastAccessTimeGreaterThan;
            TierToArchiveAfterDaysSinceLastTierChangeGreaterThan = tierToArchiveAfterDaysSinceLastTierChangeGreaterThan;
            TierToArchiveAfterDaysSinceModificationGreaterThan = tierToArchiveAfterDaysSinceModificationGreaterThan;
            TierToColdAfterDaysSinceCreationGreaterThan = tierToColdAfterDaysSinceCreationGreaterThan;
            TierToColdAfterDaysSinceLastAccessTimeGreaterThan = tierToColdAfterDaysSinceLastAccessTimeGreaterThan;
            TierToColdAfterDaysSinceModificationGreaterThan = tierToColdAfterDaysSinceModificationGreaterThan;
            TierToCoolAfterDaysSinceCreationGreaterThan = tierToCoolAfterDaysSinceCreationGreaterThan;
            TierToCoolAfterDaysSinceLastAccessTimeGreaterThan = tierToCoolAfterDaysSinceLastAccessTimeGreaterThan;
            TierToCoolAfterDaysSinceModificationGreaterThan = tierToCoolAfterDaysSinceModificationGreaterThan;
        }
    }
}
