// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * Manages a Microsoft Table in a Log Analytics (formally Operational Insights) Workspace.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as azure from "@pulumi/azure";
 *
 * const example = new azure.core.ResourceGroup("example", {
 *     name: "example-resources",
 *     location: "West Europe",
 * });
 * const exampleAnalyticsWorkspace = new azure.operationalinsights.AnalyticsWorkspace("example", {
 *     name: "example",
 *     location: example.location,
 *     resourceGroupName: example.name,
 *     retentionInDays: 30,
 * });
 * const exampleWorkspaceTableMicrosoft = new azure.loganalytics.WorkspaceTableMicrosoft("example", {
 *     name: "AppCenterError",
 *     workspaceId: exampleAnalyticsWorkspace.id,
 * });
 * ```
 *
 * ## API Providers
 *
 * <!-- This section is generated, changes will be overwritten -->
 * This resource uses the following Azure API Providers:
 *
 * * `Microsoft.OperationalInsights` - 2022-10-01
 *
 * ## Import
 *
 * Log Analytics Workspace Table Microsofts can be imported using the `resource id`, e.g.
 *
 * ```sh
 * $ pulumi import azure:loganalytics/workspaceTableMicrosoft:WorkspaceTableMicrosoft example /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/mygroup1/providers/Microsoft.OperationalInsights/workspaces/workspace1/tables/table1
 * ```
 */
export class WorkspaceTableMicrosoft extends pulumi.CustomResource {
    /**
     * Get an existing WorkspaceTableMicrosoft resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: WorkspaceTableMicrosoftState, opts?: pulumi.CustomResourceOptions): WorkspaceTableMicrosoft {
        return new WorkspaceTableMicrosoft(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'azure:loganalytics/workspaceTableMicrosoft:WorkspaceTableMicrosoft';

    /**
     * Returns true if the given object is an instance of WorkspaceTableMicrosoft.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is WorkspaceTableMicrosoft {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === WorkspaceTableMicrosoft.__pulumiType;
    }

    /**
     * One or more `column` blocks as defined below.
     */
    declare public readonly columns: pulumi.Output<outputs.loganalytics.WorkspaceTableMicrosoftColumn[] | undefined>;
    /**
     * A description of the table.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * The display name of the table.
     */
    declare public readonly displayName: pulumi.Output<string | undefined>;
    /**
     * Specifies a list of table labels.
     */
    declare public readonly labels: pulumi.Output<string[] | undefined>;
    /**
     * The name which should be used for this Log Analytics Workspace Table Microsoft. Possible values are `Alert`, `AppCenterError`, `ComputerGroup`, `InsightsMetrics`, `Operation` and `Usage`. Changing this forces a new Log Analytics Workspace Table Microsoft to be created.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The table retention in days, between `4` and `730`.
     *
     * > **Note:** `retentionInDays` must be less than or equal to `totalRetentionInDays`.
     */
    declare public readonly retentionInDays: pulumi.Output<number | undefined>;
    /**
     * The list of solutions associated with this table.
     */
    declare public /*out*/ readonly solutions: pulumi.Output<string[]>;
    /**
     * A `standardColumn` block as defined below.
     */
    declare public /*out*/ readonly standardColumns: pulumi.Output<outputs.loganalytics.WorkspaceTableMicrosoftStandardColumn[]>;
    /**
     * The table total retention in days, between `4` and `4383`.
     */
    declare public readonly totalRetentionInDays: pulumi.Output<number | undefined>;
    /**
     * The ID of the Log Analytics Workspace. Changing this forces a new Log Analytics Workspace Table Microsoft to be created.
     */
    declare public readonly workspaceId: pulumi.Output<string>;

    /**
     * Create a WorkspaceTableMicrosoft resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: WorkspaceTableMicrosoftArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: WorkspaceTableMicrosoftArgs | WorkspaceTableMicrosoftState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as WorkspaceTableMicrosoftState | undefined;
            resourceInputs["columns"] = state?.columns;
            resourceInputs["description"] = state?.description;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["labels"] = state?.labels;
            resourceInputs["name"] = state?.name;
            resourceInputs["retentionInDays"] = state?.retentionInDays;
            resourceInputs["solutions"] = state?.solutions;
            resourceInputs["standardColumns"] = state?.standardColumns;
            resourceInputs["totalRetentionInDays"] = state?.totalRetentionInDays;
            resourceInputs["workspaceId"] = state?.workspaceId;
        } else {
            const args = argsOrState as WorkspaceTableMicrosoftArgs | undefined;
            if (args?.workspaceId === undefined && !opts.urn) {
                throw new Error("Missing required property 'workspaceId'");
            }
            resourceInputs["columns"] = args?.columns;
            resourceInputs["description"] = args?.description;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["labels"] = args?.labels;
            resourceInputs["name"] = args?.name;
            resourceInputs["retentionInDays"] = args?.retentionInDays;
            resourceInputs["totalRetentionInDays"] = args?.totalRetentionInDays;
            resourceInputs["workspaceId"] = args?.workspaceId;
            resourceInputs["solutions"] = undefined /*out*/;
            resourceInputs["standardColumns"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(WorkspaceTableMicrosoft.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering WorkspaceTableMicrosoft resources.
 */
export interface WorkspaceTableMicrosoftState {
    /**
     * One or more `column` blocks as defined below.
     */
    columns?: pulumi.Input<pulumi.Input<inputs.loganalytics.WorkspaceTableMicrosoftColumn>[] | undefined>;
    /**
     * A description of the table.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * The display name of the table.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Specifies a list of table labels.
     */
    labels?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The name which should be used for this Log Analytics Workspace Table Microsoft. Possible values are `Alert`, `AppCenterError`, `ComputerGroup`, `InsightsMetrics`, `Operation` and `Usage`. Changing this forces a new Log Analytics Workspace Table Microsoft to be created.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The table retention in days, between `4` and `730`.
     *
     * > **Note:** `retentionInDays` must be less than or equal to `totalRetentionInDays`.
     */
    retentionInDays?: pulumi.Input<number | undefined>;
    /**
     * The list of solutions associated with this table.
     */
    solutions?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * A `standardColumn` block as defined below.
     */
    standardColumns?: pulumi.Input<pulumi.Input<inputs.loganalytics.WorkspaceTableMicrosoftStandardColumn>[] | undefined>;
    /**
     * The table total retention in days, between `4` and `4383`.
     */
    totalRetentionInDays?: pulumi.Input<number | undefined>;
    /**
     * The ID of the Log Analytics Workspace. Changing this forces a new Log Analytics Workspace Table Microsoft to be created.
     */
    workspaceId?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a WorkspaceTableMicrosoft resource.
 */
export interface WorkspaceTableMicrosoftArgs {
    /**
     * One or more `column` blocks as defined below.
     */
    columns?: pulumi.Input<pulumi.Input<inputs.loganalytics.WorkspaceTableMicrosoftColumn>[] | undefined>;
    /**
     * A description of the table.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * The display name of the table.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * Specifies a list of table labels.
     */
    labels?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The name which should be used for this Log Analytics Workspace Table Microsoft. Possible values are `Alert`, `AppCenterError`, `ComputerGroup`, `InsightsMetrics`, `Operation` and `Usage`. Changing this forces a new Log Analytics Workspace Table Microsoft to be created.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The table retention in days, between `4` and `730`.
     *
     * > **Note:** `retentionInDays` must be less than or equal to `totalRetentionInDays`.
     */
    retentionInDays?: pulumi.Input<number | undefined>;
    /**
     * The table total retention in days, between `4` and `4383`.
     */
    totalRetentionInDays?: pulumi.Input<number | undefined>;
    /**
     * The ID of the Log Analytics Workspace. Changing this forces a new Log Analytics Workspace Table Microsoft to be created.
     */
    workspaceId: pulumi.Input<string>;
}
