// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Azure.Monitoring.Inputs
{

    public sealed class ActionRuleActionGroupConditionTargetResourceTypeArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The operator for a given condition. Possible values are `Equals` and `NotEquals`.
        /// </summary>
        [Input("operator", required: true)]
        public Input<string> Operator { get; set; } = null!;

        [Input("values", required: true)]
        private InputList<string>? _values;

        /// <summary>
        /// A list of values to match for a given condition. The values should be valid resource types.
        /// </summary>
        public InputList<string> Values
        {
            get => _values ?? (_values = new InputList<string>());
            set => _values = value;
        }

        public ActionRuleActionGroupConditionTargetResourceTypeArgs()
        {
        }
    }
}
